language: java
script: cd ch.vobos.typescript.releng; mvn -Pdeploy clean install
jdk:
- openjdk6
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  global:
  - secure: ZY1tdoBajR7jroR49UvA/QhgzCy6kbAeXVw6m0zX8ytrO6HcLw7mahN/Pec5VkL9ffqHzupl+KIoyol4023O5J74X8EndU7Ecf76QEZMFG6a863cP63jE4xBpLDout9HVIpwKsyDJ7Uoc1rUrZmF3scdCP8NnB1jZS/7CUTymOU=
